// Import css files
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Poppins } from 'next/font/google';
import Navbar from '@/components/navbar/navbar'; 
import Footer from '@/components/footer/footer';
import style from './globals.css'

const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Pdf Converter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main className={style.maincontent}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}